# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-sql-dashboard
  version: "1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-sql-dashboard-${{ version }}.tar.gz
  sha256: 7bc8ee6cb212d74147216e31ec392e29f5c16bdcb5cc8e76a3715f0d527713a9

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=3.0
    - markdown
    - bleach

tests:
  - python:
      imports:
        - django_sql_dashboard
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Django app for building dashboards using raw SQL queries
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/simonw/django-sql-dashboard

extra:
  recipe-maintainers:
    - rxm7706
